In [1]:
import os

import numpy as np

import torch
import torchvision

import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as transforms
import torch.distributions as dist

from torch.utils.tensorboard import SummaryWriter

In [3]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10, 10)
    self.fc2 = nn.Linear(10, 1)
  def forward(self, x):
    x = self.fc1(x)
    x = self.fc2(x)
    return x

In [4]:
a = Net()

In [6]:
a.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-0.1706, -0.0693,  0.2451,  0.1571, -0.1886, -0.0547,  0.1544, -0.0265,
                       -0.2236,  0.1478],
                      [-0.2065,  0.0422,  0.0013,  0.1881, -0.0232, -0.1153,  0.2834, -0.0248,
                        0.3069, -0.1725],
                      [-0.1847,  0.1047,  0.2160,  0.1431,  0.3077,  0.2041, -0.0144,  0.2053,
                       -0.0377,  0.2422],
                      [-0.2639, -0.1555,  0.1987,  0.2746, -0.0457,  0.1880,  0.1014,  0.1908,
                        0.0134,  0.0283],
                      [-0.0582, -0.0103, -0.0863,  0.2555, -0.0546,  0.1496, -0.0124,  0.1775,
                        0.2454,  0.3153],
                      [ 0.1427,  0.1187,  0.1878,  0.2006,  0.1722,  0.0325,  0.2100, -0.1817,
                       -0.2133, -0.0115],
                      [ 0.2287, -0.1166, -0.1856,  0.2529,  0.1001, -0.2726, -0.0525, -0.3024,
                        0.1736, -0.0530],
             

In [7]:
h_t = a

In [10]:
a = torch.tensor([1])

In [11]:
a

tensor([1])

In [14]:
a = h_t.fc1.weight

In [19]:
cat = torch.Tensor(h_t.fc1.weight)

In [39]:
weight1 = torch.randn([3])
weight2 = torch.randn([2])
weight2 = F.pad(weight2, (0, 1),  mode='constant', value=0)

In [40]:
torch.add(weight1, weight2)

tensor([0.2593, 0.5714, 0.4501])

In [41]:
weight1

tensor([ 0.8774, -1.0699,  0.4501])

In [42]:
weight2

tensor([-0.6181,  1.6413,  0.0000])